enum going
{
	going_null = 0,
      forward = 1,
	backward = 2
};
enum direction
{
      direction_null = 0,
      left = 1,
	right = 2
};

struct DriveAssembly
{
    going drive;
    direction steer;
};

